import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";

const InterFont = Inter({
  weight: ["700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${InterFont.className} `}>
        <div className="size-150 fixed -translate-x-27.5 top-0 bottom-0 left-0  rounded-full border -z-10 border-primary max-md:size-50"></div>
        {children}{" "}
        <div className="h-150 w-150 -z-10 fixed translate-x-27.5 top-[45%] bottom-0 right-0  rounded-full border border-primary max-md:size-50"></div>
      </body>
    </html>
  );
}
